# Assignment 1: Small Image Dataset 

Implement a function that, given an input vector p whose elements are +1s and -1s, and a scalar value d (within 0.05 and 1) returns a perturbed/distorted version of the input vector, flipping (i.e., changing the sign) of the d*100 % its elements.

You can find an example of such a function, implemented in Python and MATLAB, in “distort_image” file (in the archive download at point 1). 

You can interpret the input p as an input image, and d as the percentage of distortion to apply.


In [1]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt
import pandas as pd
import json
from sklearn.model_selection import GridSearchCV
from sklearn.utils import shuffle
import itertools
import random

from hopfield import Hopfield

In [2]:
p0 = pd.read_csv('./data/p0.csv', header=None).to_numpy()
p1 = pd.read_csv('./data/p1.csv', header=None).to_numpy()
p2 = pd.read_csv('./data/p2.csv', header=None).to_numpy()
d = np.random.uniform(low=0.05, high=1.0, size=None)

In [3]:
#through this unction we obtain a distorted version of the patterns
#those will be fed to the network as the x (neuron states)
def distort_image(im, prop):
    if prop < 0 or prop > 1:
        print('Out-of-bound proportion: going to default 0.05')
        prop = 0.05  # Default
    
    # Calculation of the number of elements to be distorted.
    total_elements = im.size
    num_to_distort = round(total_elements * prop)
    
    # Random selection of the indices of the elements to be distorted.
    indices_to_distort = np.random.permutation(total_elements)[:num_to_distort]
    
    # Flattening the image to facilitate access to and editing of elements.
    im_flat = im.flatten()
    im_flat[indices_to_distort] = -im_flat[indices_to_distort]
    
    # Return of the image to its original format after distortion.
    return im_flat.reshape(im.shape)

In [4]:
#get the initial states 
x0 = distort_image(p0, d)
x1 = distort_image(p1, d)
x2 = distort_image(p2, d)
x0, x1, x2

(array([[ 1],
        [-1],
        [ 1],
        ...,
        [ 1],
        [ 1],
        [ 1]], dtype=int64),
 array([[ 1],
        [ 1],
        [ 1],
        ...,
        [-1],
        [ 1],
        [ 1]], dtype=int64),
 array([[1],
        [1],
        [1],
        ...,
        [1],
        [1],
        [1]], dtype=int64))

In [5]:
x0.shape, x1.shape, x2.shape

((1024, 1), (1024, 1), (1024, 1))

In [6]:
input_data = np.array([x0, x1, x2]).squeeze()
input_data.shape

(3, 1024)

In [7]:
patterns = np.array([p0, p1, p2]).squeeze()
patterns.shape

(3, 1024)

In [8]:
hf = Hopfield(input_data, patterns)
hf()

Weight matrix:  (1024, 1024) input matrix:  (1024, 3)
(3,) [(1024,), (1024,), (1024,)]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1024 is different from 3)