# Assignment 1: Small Image Dataset 

Implement a function that, given an input vector p whose elements are +1s and -1s, and a scalar value d (within 0.05 and 1) returns a perturbed/distorted version of the input vector, flipping (i.e., changing the sign) of the d*100 % its elements.

You can find an example of such a function, implemented in Python and MATLAB, in “distort_image” file (in the archive download at point 1). 

You can interpret the input p as an input image, and d as the percentage of distortion to apply.


In [1]:
import numpy as np
from numpy import linalg
import matplotlib.pyplot as plt
import pandas as pd
import json
from sklearn.model_selection import GridSearchCV
from sklearn.utils import shuffle
import itertools
import random 
import glob

from hopfield import Hopfield

In [2]:
seed = 0
random.seed(seed)
np.random.seed(seed)

In [3]:
patterns = [pd.read_csv(filename).to_numpy() 
            for filename in glob.iglob('./data/p*.csv', 
                                    recursive = False)]
patterns = np.array(patterns).squeeze()
patterns.shape

(3, 1023)

In [4]:
#through this unction we obtain a distorted version of the patterns
#those will be fed to the network as the x (neuron states)
def distort_image(im, prop):
    if prop < 0 or prop > 1:
        print('Out-of-bound proportion: going to default 0.05')
        prop = 0.05  # Default
    
    # Calculation of the number of elements to be distorted.
    total_elements = im.size
    num_to_distort = round(total_elements * prop)
    
    # Random selection of the indices of the elements to be distorted.
    indices_to_distort = np.random.permutation(total_elements)[:num_to_distort]
    
    # Flattening the image to facilitate access to and editing of elements.
    im_flat = im.flatten()
    im_flat[indices_to_distort] = -im_flat[indices_to_distort]
    
    # Return of the image to its original format after distortion.
    return im_flat.reshape(im.shape)

In [5]:
distortion = [0.05, 0.1, 0.25]
dist_img = [distort_image(p, d) for p in patterns for d in distortion]
dist_img # 3 patterns x 3 distortion values

[array([-1,  1, -1, ..., -1, -1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1, -1, -1], dtype=int64),
 array([-1, -1, -1, ...,  1,  1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1,  1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1, -1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1,  1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1, -1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1,  1, -1], dtype=int64),
 array([-1, -1, -1, ..., -1,  1, -1], dtype=int64)]

In [6]:
for img in dist_img:
    hf = Hopfield(img, patterns)
    hf()
    #plots

[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
[[0.7341153470185728, 0.7908113391984359, 0.855327468230694]] [-990519.0] [-1 -1 -1 ... -1 -1 -1]
